version: '3.8'

services:
  graphql:
    build: .
    container_name: graphql_container
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - app-network
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: